name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  lottie:
  http: ^1.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - app_assets/
    - app_assets/images/
    - app_assets/animations/